#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
merge_library.py
================
ממזג את local_library_adults.js ו-local_library_kids.js לקובץ אחד:
  data/local_library_merged.js  →  var LOCAL_LIBRARY = [...]

ספרי ילדים מסומנים ב-audience/sub_genre/genres ומסוננים בזמן-ריצה ב-app.js.

שימוש:
    py -3 merge_library.py

שלב הבא:
    py -3 compute_embeddings.py --input data/local_library_merged.js --output data/embeddings_merged.js
"""

import json, re, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

ADULTS_PATH = r'C:\Users\hacmo\Desktop\MyWebsite\library\data\local_library_adults.js'
KIDS_PATH   = r'C:\Users\hacmo\Desktop\MyWebsite\library\data\local_library_kids.js'
MERGED_PATH = r'C:\Users\hacmo\Desktop\MyWebsite\library\data\local_library_merged.js'


def load_js(path):
    with open(path, encoding='utf-8-sig') as f:
        content = f.read()
    m = re.search(r'var LOCAL_LIBRARY(?:_KIDS)?\s*=\s*(\[.*\])\s*;', content, re.DOTALL)
    if not m:
        raise ValueError(f'לא נמצא LOCAL_LIBRARY ב-{path}')
    return json.loads(m.group(1))


def main():
    print('טוען ספרייה מבוגרים...')
    adults = load_js(ADULTS_PATH)
    print(f'  {len(adults)} ספרים')

    print('טוען ספרייה ילדים/נוער...')
    kids = load_js(KIDS_PATH)
    print(f'  {len(kids)} ספרים')

    adult_ids = {b['id'] for b in adults}
    dupes = [b for b in kids if b['id'] in adult_ids]
    if dupes:
        print(f'אזהרה: {len(dupes)} ספרים עם ID כפול — מדלג')
    kids = [b for b in kids if b['id'] not in adult_ids]

    merged = adults + kids
    print(f'\nסה"כ: {len(merged)} ספרים ({len(adults)} מבוגרים + {len(kids)} ילדים/נוער)')

    with open(MERGED_PATH, 'w', encoding='utf-8') as f:
        f.write('// auto-generated by merge_library.py — אל תערוך ידנית\n')
        f.write('// ספרי ילדים/נוער מסוננים ב-app.js בזמן-ריצה (isKidsBook)\n')
        f.write('var LOCAL_LIBRARY = ')
        f.write(json.dumps(merged, ensure_ascii=False, indent=2))
        f.write(';\n')

    print(f'נשמר: {MERGED_PATH}')
    print('\nשלב הבא:')
    print('  py -3 compute_embeddings.py --input data/local_library_merged.js --output data/embeddings_merged.js')
    print('\n✓ בוצע')


if __name__ == '__main__':
    main()
