#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
split_library.py
================
מפצל את local_library_described.js לשני קבצים:
  - local_library_adults.js  (ספרות מבוגרים + עיון)
  - local_library_kids.js    (ילדים + נוער + YA)

שימוש:
    py -3 split_library.py
"""

import json, re, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

SRC_PATH    = r'C:\Users\hacmo\Desktop\MyWebsite\library\data\local_library_described.js'
ADULTS_PATH = r'C:\Users\hacmo\Desktop\MyWebsite\library\data\local_library_adults.js'
KIDS_PATH   = r'C:\Users\hacmo\Desktop\MyWebsite\library\data\local_library_kids.js'

KIDS_SUB_GENRES = {'ספרות ילדים', 'גן ילדים', 'ראשית קריאה', 'ספרות נוער (YA)'}


def is_kids_book(b):
    audience = b.get('audience') or []
    if isinstance(audience, str):
        audience = [audience]
    if 'ילדים' in audience or 'נוער' in audience:
        return True
    if b.get('sub_genre') in KIDS_SUB_GENRES:
        return True
    genres = b.get('genres') or []
    if 'ילדים ונוער' in genres:
        return True
    return False


def write_js(books, path, var_name='LOCAL_LIBRARY'):
    content = (
        f'// Auto-generated by split_library.py — אל תערוך ידנית\n'
        f'var {var_name} = '
        + json.dumps(books, ensure_ascii=False, indent=2)
        + ';\n'
    )
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)


def main():
    print('טוען ספרייה...')
    with open(SRC_PATH, encoding='utf-8-sig') as f:
        content = f.read()
    m = re.search(r'var LOCAL_LIBRARY\s*=\s*(\[.*\])\s*;', content, re.DOTALL)
    if not m:
        print('שגיאה: לא נמצא LOCAL_LIBRARY')
        return
    books = json.loads(m.group(1))
    print(f'  סה"כ: {len(books)} ספרים')

    adults = [b for b in books if not is_kids_book(b)]
    kids   = [b for b in books if is_kids_book(b)]

    print(f'  מבוגרים: {len(adults)}')
    print(f'  ילדים/נוער: {len(kids)}')

    # בדיקת כיסוי — ספרים שלא סווגו בשום קטגוריה
    assert len(adults) + len(kids) == len(books), 'שגיאה: ספרים אבדו בפיצול'

    write_js(adults, ADULTS_PATH)
    print(f'  נשמר: {ADULTS_PATH}')

    write_js(kids, KIDS_PATH)
    print(f'  נשמר: {KIDS_PATH}')

    print('\nדוגמת ילדים/נוער:')
    for b in kids[:5]:
        print(f'  [{b.get("audience")}] [{b.get("sub_genre")}] {b.get("title")}')

    print('\n✓ בוצע')
    print('\nשלב הבא: py -3 compute_embeddings.py --input data/local_library_adults.js --output data/embeddings_adults.js')


if __name__ == '__main__':
    main()
